# .github/workflows/ci.yml

name: Run CLI Commands on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)"
      - name: Flow CLI Version
        run: flow-c1 version
      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Run tests
        run: flow-c1 test test/band_oracle_tests.cdc