# .github/workflows/ci.yml

name: Run CLI Commands on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Tests
      run: |
        flow-c1 test test/band_oracle_tests.cdc