# .github/workflows/ci.yml

name: Run CLI Commands on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flow cli
      run: |
        sudo sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)"
        echo "/root/.local/bin" >> $GITHUB_PATH
        export PATH=$PATH:/root/.local/bin

    - name: Debugging Path
      run: |
        echo $PATH
        ls /root/.local/bin

    - name: Run Tests
      run: |
        set -e
        flow-c1 test test/band_oracle_tests.cdc